# Generated by Django 2.2 on 2019-06-14 10:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafficevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='street',
            name='commune',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='dashboard.Commune'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficevent',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_dashboard.trafficevent_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='street',
            name='path',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
        ),
        migrations.CreateModel(
            name='StreetSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_type', models.CharField(choices=[('DI', 'Dirt'), ('ASP', 'Asphalt'), ('CON', 'Concrete')], max_length=3)),
                ('segment_path', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('parent_segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_segments', to='dashboard.StreetSegment')),
                ('street', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='dashboard.Street')),
            ],
        ),
        migrations.CreateModel(
            name='RoadWorks',
            fields=[
                ('trafficevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.TrafficEvent')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('street_segments', models.ManyToManyField(to='dashboard.StreetSegment')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('dashboard.trafficevent',),
        ),
    ]
