# Generated by Django 2.2 on 2019-06-14 14:53

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190614_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadworks',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trafficevent',
            options={},
        ),
        migrations.AddField(
            model_name='roadworks',
            name='description',
            field=models.TextField(default='N.A.'),
        ),
        migrations.AlterUniqueTogether(
            name='truck',
            unique_together={('obu_id', 'measurement_date')},
        ),
        migrations.AddIndex(
            model_name='truck',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['measurement_date'], name='daily_summary_idx'),
        ),
    ]
