# Generated by Django 2.2 on 2019-06-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190614_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='area',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
