# Generated by Django 2.2 on 2019-06-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_commune_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='postal_code',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
