# Generated by Django 2.2 on 2019-09-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190719_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='average_velocity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='country_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='euro_value',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='weight_category',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
