# Generated by Django 2.2 on 2019-12-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_street_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='one_way',
            field=models.CharField(choices=[('F', 'Line direction'), ('T', 'Oposite diretion'), ('B', 'Two Way')], default='B', max_length=1),
        ),
    ]
