# Generated by Django 2.2 on 2019-12-20 15:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20191220_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='path',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326),
        ),
    ]
