# Generated by Django 2.2 on 2020-07-15 12:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200424_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='typical_traffic',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='street',
            name='typical_traffic',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
